/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package co.com.sp.capapersistencia.excepciones;

public class PersistenceException extends Exception{

	private static final long serialVersionUID = -3152613949782416390L;
	
	protected Throwable throwable;

	public PersistenceException(String message)
	{
		super(message);
	}

	public PersistenceException(String message, Throwable throwable)
	{
		super(message);
		this.throwable = throwable;
	}

	public Throwable getCause()
	{
		return throwable;
	}

}
